lib/easypost/address.rb, spec/address_spec.rb
EasyPost::Address.create_and_verify could not invoke
raise_verification_failure instance method, so it’s
now a class method.
At line https://github.com/EasyPost/easypost-ruby/compare/master...dimroc:master#diff-005a9ba9d83f4a1247ea9d044f86c63bL26 you can see that the class method is trying to invoke
`raise_verification_failure` which is an instance method.
=> Fixed Address.create_and_verify to properly raise_verification_failure

lib/easypost/pickup.rb
adding pickup cancel method and endpoint, missing from ruby gem, tested and works as expected
=> adding pickup cancel method and endpoint, missing from ruby gem

spec/user_spec.rb
noticed that the order of the keys on this test were incorrect. The test api key is always created first.
=> change order of api_keys on user test

lib/easypost/util.rb, spec/shipment_spec.rb, spec/support/constant.rb
When using Amazon MWS new options are required.
fulfiller_order_id: "1234567890",
fulfiller_order_items: [
{
id: "1234567890",
quantity: "1",
}
]
On shipment create, it was trying to convert fulfiller_order_items to an easypost object because it has an 'id' key inside it. This would throw an argument error.
easypost-2.7.1/lib/easypost/util.rb:84:in `convert_to_easypost_object': bad value for range (ArgumentError)
This is a patch to rescue for that error since it shouldn't be trying to convert this option to an easypost object in the first place.
=> rescue argument error when converting response to easypost object

lib/easypost.rb
This enables validation of our TLS/SSL certificate by default.
This verification has been disabled since the first commit to this repo with no explanation. I imagine someone was using an intercepting proxy to test things and didn't want to set up a trust store for its root CA.
I tested that without this change I can freely intercept sessions using `mitmproxy` and that with this change I cannot.
Fixes #72.
=> enable certificate verification by default

.travis.yml, easypost.gemspec, lib/easypost.rb, spec/pickup_spec.rb, spec/shipment_spec.rb, spec/spec_helper.rb
Since Ruby 2.4 was EOL'd in 2016. I vote to remove support for it and its predecessors. Anyone object?
=> Update Dependencies, fix tests, and test against ruby2.6/7

lib/easypost/util.rb
The refund and the new shipment invoice report were missing from the prefix and type list. I've added them here.
=> Adding Shipment Invoice & Refund Report to Prefix & Type Lists

lib/easypost/object.rb, spec/object_spec.rb
In 3.0.x construct_from worked properly if you constructed from a hash where the key was a symbol, or a string.
And given the values are always looked up by converting the key to a string, we should store it the same way:
```
def [](k)
@values[k.to_s]
end
```
Now it won't matter if you lookup/store as a string or a symbol.
=> When constructing an easypost object, convert the key to a string

lib/easypost.rb, lib/easypost/error.rb, spec/cassettes/easypost/EasyPost_make_request_stores_the_http_body_on_the_error.yml, spec/easypost_spec.rb
Before the 3.1.x versions of this gem you could access the raw http response by calling `e.http_body`.
This PR simply adds this method back to the error object.
This is very important for debugging purposes and we're unable to upgrade to the latest version of the gem as we log every request to aid in debugging.
=> Expose http_body on the Easypost::Error object

lib/easypost/shipment.rb, lib/easypost/util.rb, spec/cassettes/shipment/EasyPost_Shipment_lowest_rate_domestic_shipment_doesn_t_modify_carriers_array.yml, spec/cassettes/shipment/EasyPost_Shipment_lowest_rate_domestic_shipment_doesn_t_modify_services_array.yml, spec/shipment_spec.rb, spec/util_spec.rb
This is some fixes on top of #71 to make it work a bit more cleanly.
Closes #71.
=> Prevent lowest_rate from modifying carriers and services parameters

lib/easypost/object.rb, spec/object_spec.rb
This ensures the accessors will return the correct value when constructing an `EasyPostObject` with a hash using symbols for the keys.
Example:
**Before**
```rb
addr = EasyPost::EasyPostObject.construct_from(zip: "90210")
addr.zip # => nil
```
**After**
```rb
addr = EasyPost::EasyPostObject.construct_from(zip: "90210")
addr.zip # => "90210"
```
=> Look up EasyPostObject attributes by string key

lib/easypost.rb, lib/easypost/address.rb, lib/easypost/batch.rb, lib/easypost/carrier_account.rb, lib/easypost/customs_info.rb, lib/easypost/customs_item.rb, lib/easypost/error.rb, lib/easypost/event.rb, lib/easypost/insurance.rb, lib/easypost/item.rb, lib/easypost/object.rb, lib/easypost/order.rb, lib/easypost/parcel.rb, lib/easypost/pickup.rb, lib/easypost/pickup_rate.rb, lib/easypost/postage_label.rb, lib/easypost/print_job.rb, lib/easypost/printer.rb, lib/easypost/rate.rb, lib/easypost/refund.rb, lib/easypost/report.rb, lib/easypost/resource.rb, lib/easypost/scan_form.rb, lib/easypost/shipment.rb, lib/easypost/tracker.rb, lib/easypost/user.rb, lib/easypost/util.rb, lib/easypost/webhook.rb
I would eventually like to get Rubocop working on this repository, but basically every line fails Rubocop today.
This is the first change, which helps prevent a whole mess of confusion around relative-scoped modules and classes. It changes almost every line of the application. The only changes are making all of the class/module names collapsed, fixing indentation, and fixing the half-dozen places where we were calling classes relatively (e.g., changing `Error.new` into `EasyPost::Error.new`).
=> flatten all classes and modules; fully-qualify scopes

lib/easypost/address.rb
Method `create_and_verify` was checking for `response.has_key?(:address)` whereas the returned response json has string as keys instead of symbol. This resulted in unnecessary raising `EasyPost::Error.new("Unable to verify address.")`
=> Replace symbol keys with string keys in create_and_verify

spec/address_spec.rb, spec/cassettes/address/EasyPost_Address_create_and_verify_for_a_valid_address_should_work_correctly.yml
The `create_and_verify` function has been broken since 8c1dbd09a45bc12d93ee520ccd81e7f3b5f66432 (version 3.1.0). We had no tests for the happy case.
The underlying bug was fixed in #108; this adds a test to hopefully eliminate future breaking.
=> add a spec for a successful addresses#create_and_verify call

CHANGELOG.md, lib/easypost/tracker.rb
This endpoint was introduced as an experiment in 2015 and never documented. It has no users and is being removed.
=> remove 2015-vintage experimental "all_updated" action on trackers

lib/easypost/object.rb, spec/object_spec.rb
This adds the `deconstruct_keys` method to the EasyPostObject class so that you can pattern match with the objects directly.
I'm using this to define logic for handling specific errors from carriers
```ruby
shipment.messages.each do |message|
case message
in { type: /rate_error/i, carrier: /gso/i, message: /ship date/i }
else
end
end
```
I tried to avoid symbolizing the keys, but I learned that pattern matching a hash requires symbol keys, so the `deconstruct_keys` implementation converts the keys to symbols.
=> Support pattern matching in Ruby 2.7+

lib/easypost.rb, lib/easypost/tax_identifier.rb, lib/easypost/util.rb
Adds the new `TaxIdentifier` object, although technically not needed to start using the TaxIdentifer object, good to add anyway.
An example of using this is simply passing the following on a shipment create call:
```ruby
tax_identifiers: [
{
entity: 'RECEIVER',
tax_id_type: 'IOSS',
tax_id: '12345',          
issuing_country: 'GB',
},
]
```
=> feat: adds TaxIdentifier object

README.md, spec/spec_helper.rb
Replaces the hardcoded API key in `spec_helper` with `ENV` to retrieve the API_KEY env variable. (eg: `API_KEY=123 bundle exec rspec`)
We have this pattern in other client libraries.
=> chore: replace API key in spec_helper with env var

CHANGELOG.md, lib/easypost/batch.rb
Removes the unusable and deprecated `stamp_and_barcode_by_reference` method from the Batch object.
=> chore: remove stamp_and_barcode_by_reference method

.gitignore, lib/easypost/tracker.rb, spec/cassettes/tracker/EasyPost_Tracker_create_list_creates_trackers_in_bulk_from_a_list_of_tracking_codes.yml, spec/easy_post/tracker_spec.rb
Currently, the user has to pass **trackers** as the key when calling the **create_list** method in the Tracker class. If the user mistypes the trackers, an error can be thrown from the API. Instead of asking the user to input the key, we are going to do that for the user in the method. 
Testing: re-record the cassette and make sure everything works.
=> improve the create_list in Tracker class.

CHANGELOG.md, lib/easypost/parcel.rb, lib/easypost/rate.rb, lib/easypost/shipment.rb
* Explicitly returns an error of "not implemented" for `Rate.all` and `Parcel.all`
* Removes the `Shipment.get_rates` function as shipments already contain rates. If you need to get new rates for a shipment, use the `Shipment.regenerate_rates` function instead
I did these together as they are all breaking changes and needed prior to our next release.
=> chore: remove the Shipment.get_rates function

lib/easypost/resource.rb
The big misnomer is `.all` which doesn't list ALL resources, it just lists one page.
By turning every resource into an `Enumerable` extension you now do very healthy, memory conscious iterator patterns with stdlib.
For instance:
```ruby
EasyPost::Address.lazy.select { |address| address.state == "ME" }.take(2)
EasyPost::Address.lazy.take(100).map(&:country).tally
```
=> feat: Resource.each enumerates resources across pages

spec/cassettes/shipment/EasyPost_Shipment_create_creates_a_shipment_when_only_IDs_are_used.yml, spec/shipment_spec.rb
Adds a test when only IDs are passed to object creation. This was brought up as a way to check behavior across all libs due to: https://github.com/EasyPost/easypost-node/issues/222
=> chore: add shipment ID test

CHANGELOG.md, lib/easypost/object.rb, lib/easypost/report.rb, spec/cassettes/report/EasyPost_Report_create_creates_a_report_with_custom_additional_columns.yml, spec/cassettes/report/EasyPost_Report_create_creates_a_report_with_custom_columns.yml, spec/report_spec.rb
Based on https://github.com/EasyPost/easypost-csharp/pull/234
This PR:
- Adds support for specifying `columns` and `additional_columns` (both lists of strings) in the `parameters` dictionary passed into `EasyPost::Report.create(parameters)`
- Adds unit tests for this feature
Unfortunately, since the API response does not indicate the columns used for a report, the only way to ensure the report actually includes the columns requested would be to make a live API call, download the generated CSV report and parse its column headers. That is a complex unit test with many points of failure and prevents us from using VCR.
Instead, we simply assume that if no error is thrown during the API call to generate and retrieve the report, that the report contains the correct columns. If it doesn't, that …
=> [feat] Support for `columns` and `additional_columns` on Report creation

lib/easypost/report.rb, spec/cassettes/report/EasyPost_Report_create_creates_a_report_with_custom_additional_columns.yml, spec/cassettes/report/EasyPost_Report_create_creates_a_report_with_custom_columns.yml
- Report columns go in JSON body, not query params
- Re-record cassettes
=> Report `columns` and `additional_columns` sent via body rather than query

CHANGELOG.md, lib/easypost/address.rb, spec/address_spec.rb, spec/cassettes/address/EasyPost_Address_create_and_verify_creates_a_verified_address.yml, spec/cassettes/address/EasyPost_Address_create_creates_an_address_with_verify_param.yml, spec/cassettes/address/EasyPost_Address_verify_verifies_an_already_created_address.yml, spec/refund_spec.rb, spec/support/fixture.rb
- Removes the unusable `carrier` param from `Address.create_and_verify` along with the dead `message` conditional check
- Updates a few address assertions to match internal API changes
=> chore: remove dead message and carrier address verify code

README.md, spec/cassettes/pickup/EasyPost_Pickup_buy_buys_a_pickup.yml, spec/cassettes/pickup/EasyPost_Pickup_cancel_cancels_a_pickup.yml, spec/cassettes/pickup/EasyPost_Pickup_create_creates_a_pickup.yml, spec/cassettes/pickup/EasyPost_Pickup_retrieve_retrieves_a_pickup.yml, spec/cassettes/report/EasyPost_Report_all_retrieves_all_reports.yml, spec/cassettes/report/EasyPost_Report_create_creates_a_report.yml, spec/cassettes/report/EasyPost_Report_create_creates_a_report_with_custom_additional_columns.yml, spec/cassettes/report/EasyPost_Report_create_creates_a_report_with_custom_columns.yml, spec/cassettes/report/EasyPost_Report_retrieve_retrieves_a_report.yml, spec/report_spec.rb, spec/support/fixture.rb, spec/webhook_spec.rb
Reverts to hard-coded dates to keep VCR happy into the future, simplifies the usage by consolidating the number of dates needed.
=> fix: revert to hard-coded test dates

CHANGELOG.md, lib/easypost/order.rb, lib/easypost/pickup.rb, lib/easypost/shipment.rb, lib/easypost/util.rb, spec/cassettes/order/EasyPost_Order_lowest_rate_tests_various_usage_alterations_of_the_lowest_rate_method.yml, spec/cassettes/pickup/EasyPost_Pickup_buy_buys_a_pickup.yml, spec/cassettes/pickup/EasyPost_Pickup_cancel_cancels_a_pickup.yml, spec/cassettes/pickup/EasyPost_Pickup_create_creates_a_pickup.yml, spec/cassettes/pickup/EasyPost_Pickup_lowest_rate_tests_various_usage_alterations_of_the_lowest_rate_method.yml, spec/cassettes/pickup/EasyPost_Pickup_retrieve_retrieves_a_pickup.yml, spec/cassettes/shipment/EasyPost_Shipment_get_lowest_smartrate_gets_the_lowest_smartrate_from_a_list_of_smartrates.yml, spec/cassettes/shipment/EasyPost_Shipment_get_lowest_smartrate_raises_an_error_when_no_rates_are_found_due_to_delivery_accuracy.yml, spec/cassettes/shipment/EasyPost_Shipment_get_lowest_smartrate_raises_an_error_when_no_rates_are_found_due_to_delivery_days.yml, spec/cassettes/shipment/EasyPost_Shipment_lowest_rate_tests_various_usage_alterations_of_the_lowest_rate_method.yml, spec/cassettes/shipment/EasyPost_Shipment_lowest_smartrate_gets_the_lowest_smartrate_of_a_shipment.yml, spec/cassettes/shipment/EasyPost_Shipment_lowest_smartrate_raises_an_error_when_no_rates_are_found_due_to_delivery_accuracy.yml, spec/cassettes/shipment/EasyPost_Shipment_lowest_smartrate_raises_an_error_when_no_rates_are_found_due_to_delivery_days.yml, spec/order_spec.rb, spec/pickup_spec.rb, spec/shipment_spec.rb, spec/support/fixture.rb
- Adds a `lowest_rate` function to Orders and Pickups
- Adds a `Shipment.get_lowest_smartrate` function and a `shipment.lowest_smartrate` function
Closes #64 
=> feat: adds lowest_rate to more objects

.github/workflows/ci.yml, CHANGELOG.md, lib/easypost/connection.rb
Throw an error if no API key provided instead of making a live API call with no key.
- A/B tested that this works with and without.
=> fix: throw error if no API key provided

CHANGELOG.md, lib/easypost/webhook.rb, spec/support/fixture.rb, spec/webhook_spec.rb
Adds a new function to validate if a webhook originated from EasyPost with the stored Webhook secret, if they do the function will return `event_body`, otherwise an error will be thrown.
Add three unit tests and pass
=> Add validate_webhook function

lib/easypost/object.rb, spec/object_spec.rb
A previous change started deleting `@values[:id]` on an object when we call `refresh_from`. If the keys within `values` are strings we will never set an id value for the object again.
This PR changes the line to only delete if the ids are different (in theory should never happen). And after `@values` has been refreshed, it will check if the object has `@values[:id]` set. If not, it will set it when possible. 
The original specs for `construct_from` were removed in [this commit](https://github.com/EasyPost/easypost-ruby/commit/582cc9df57c6efc0e97cf324e51471fba50a4164). I believe something should exist in the project as we use `construct_from` to create objects for our own specs with your library.
See specs
=> Ensure the Easypost object will respond to `.id` when it has one in @values

lib/easypost/customs_info.rb, lib/easypost/customs_item.rb, lib/easypost/order.rb, lib/easypost/parcel.rb, lib/easypost/payment_method.rb, lib/easypost/pickup.rb, lib/easypost/rate.rb
This just updates other `self.all` methods calls to match the call within `Resource`.
When calling `to_json` on a stubbed object I noticed `.all` was being called, and it was failing with:
```
Exception: ArgumentError: wrong number of arguments (given 2, expected 0)
--
0: /Users/beckerbi/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/easypost-4.6.0/lib/easypost/order.rb:29:in `all'
1: /Users/beckerbi/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/easypost-4.6.0/lib/easypost/resource.rb:55:in `block in each'
2: /Users/beckerbi/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/easypost-4.6.0/lib/easypost/resource.rb:54:in `loop'
3: /Users/beckerbi/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/easypost-4.6.0/lib/easypost/resource.rb:54:in `each'
```
After this change you will get the proper …
=> Match method definition within Resource

.github/workflows/ci.yml, .rubocop.yml, Makefile
- Correct commands in Makefile to use local copies of dependencies instead of global ones so we can use cache and so runs are consistent.
- Caches the lint step
=> chore: cache linting CI step

CHANGELOG.md, lib/easypost/shipment.rb, spec/cassettes/shipment/EasyPost_Shipment_buy_buys_a_shipment_with_carbon_offset_in_params_hash.yml, spec/shipment_spec.rb
- Adds support to buy a shipment by passing in `end_shipper_id`
- `with_carbon_offset` can now alternatively be passed in the `params` parameter of the `shipment.buy` function
- Adds mock test for `end_shipper_id` param
- Adds better coverage for carbon offset
100% coverage on shipment buy function:
=> feat: adds support to pass end_shipper_id to the shipment buy call

CHANGELOG.md, lib/easypost.rb
Our other libraries raise errors for HTTP status codes outside of the 2xx range. The docstring for this function even states that's the expected behavior; however, the current logic assumes that anything up until a 4xx is valid. The impact from this is expected to be minimal if noticeable at all but a good change to make regardless.
NA
=> fix: raise errors for non 2xx status codes

CHANGELOG.md, lib/easypost/error.rb, spec/error_spec.rb
- Concatenates `error.message` if it incorrectly comes back from the API as an array
Adds a new unit test to ensure this works as intended
=> fix: concatenates error.message if it is an array

easypost.gemspec, lib/easypost/carrier_account.rb, spec/carrier_account_spec.rb
This fixes CarrierAccount creation endpoint for UpsAccount and FedexAccount that according to the docs https://support.easypost.com/hc/en-us/articles/360041148012-FedEx-Account-Registration-Guide and https://support.easypost.com/hc/en-us/articles/360024355712-Setting-up-your-UPS-Account should be sent to a different endpoint.
Added tests
=> Fix CarrierAccount creation endpoint for UpsAccount and FedexAccount

lib/easypost/util.rb, spec/billing_spec.rb, spec/util_spec.rb
~~When deserializing JSON into a specific class (e.g. `EasyPost::Address`), we use the "id" and "object" keys in the JSON body to determine what class to use for deserialization. Based on debugging, it seemed extracting the value of "object" from the JSON body was not working correctly, potentially causing some objects to not be deserialized to their correct class (instead simply deserialized to the fallback `EasyPostObject` class).~~
~~This PR uses the `fetch()` function to attempt to extract the "object" key from the JSON body (with a `nil` fallback to preserve expected fallback functionality).~~
~~In initial testing, the `cls = BY_TYPE[cls_name]` line was never hit because the if-statement never evaluated to true. After this patch, the line is hit as expected (e.g. `{"object": …
=> Fix failing deserialization

easypost.gemspec
Corrects the directories that get ignored when building. This command was initially copied from our friends at Twilio but never altered for our own needs some ~8 years ago heh. We didn't even have these directories ourselves.
Inspected the gem contents with changes, looks appropriate for our needs.
=> fix: ignore directories for build

.github/workflows/ci.yml, .rubocop.yml, CHANGELOG.md, Makefile, easycop.yml, easypost.gemspec, lib/easypost/resource.rb, lib/easypost/util.rb, spec/carrier_account_spec.rb
- Drops support for Ruby 2.5
- Overhauls rubocop rules due to updates, fixes new errors, and ignores various top-level directories that rubocop was previously trying to lint that aren't ruby which results in much faster lint runs
- Bumps all deps
=> chore: drops Ruby 2.5, bumps deps

README.md, easypost.gemspec, lib/easypost/client.rb, lib/easypost/http_client.rb, spec/client_spec.rb
Reintroduce #116 into thread-safe re-architecture for upcoming `v5`
Users define a `custom_client_exec` lambda function when initializing an `EasyPost::Client`. 
Function should respond to `call(method, uri, headers, open_timeout, read_timeout, body = nil)` where:
- `uri` is the fully-qualified URL of the EasyPost endpoint, including query parameters
- `method` is the lowercase name of the HTTP method being used for the request
- `headers` is a hash with all headers needed for the request pre-populated, including authorization
- `open_timeout` is an integer
- `read_timeout` is an integer
- `body` is a string of the body data to be included in the request, or nil (e.g. GET or DELETE request)
Function should return a response object with the following properties:
- `code`: The integer …
=> [feat] Support for custom connection for Ruby client

README.md
Custom Connections section formatting is improved. Best seen in formatted view: 
- N/A
=> [chore] Fix formatting in README

CHANGELOG.md, lib/easypost/services/carrier_account.rb
- FedEx SmartPost carrier account registration should hit `/register` endpoint for creation
=> [fix] FedEx Smartpost hits register endpoint

spec/address_spec.rb, spec/cassettes/address/EasyPost_Services_Address_address_service_creates_an_address_with_an_array_verify_param.yml, spec/cassettes/address/EasyPost_Services_Address_address_service_creates_an_address_with_verify_param.yml, spec/cassettes/address/EasyPost_Services_Address_create_and_verify_creates_a_verified_address.yml, spec/cassettes/address/EasyPost_Services_Address_create_and_verify_throws_an_error_for_invalid_address_verification.yml, spec/cassettes/address/EasyPost_Services_Address_verify_verifies_an_already_created_address.yml, spec/support/vcr.rb
See https://github.com/EasyPost/easypost-csharp/pull/540 for more details.
- Update examples submodule for new "incorrect address" fixture
- Update address verification unit tests to better test target functionality
- Update unit tests, re-record cassettes as needed
=> [chore] Fix address verification unit tests

CHANGELOG.md, lib/easypost/services/billing.rb, spec/billing_spec.rb
As pointed out in #295 , a helper method in our billing service was static rather than instance-based, causing issues when calling it.
This PR makes the method a **private** instance helper method (not for end-user consumption), and updates the associated unit tests.
Closes #295 
- Unit test updated, no cassettes need to be rerecorded (test was already mock-only)
=> [fix] Instance usage of get_payment_method_info in billing service

CHANGELOG.md, lib/easypost/services/billing.rb, spec/billing_spec.rb
- Use payment method object type as fallback when determining type for fund, delete functions
- Update, add unit test to confirm legacy (by ID prefix) and new (by object type) both work to determine payment method type
=> [bug] Cannot determine payment method when funding/deleting

easypost.gemspec, lib/easypost/services/address.rb, lib/easypost/services/batch.rb, lib/easypost/services/carrier_account.rb, lib/easypost/services/carrier_type.rb, lib/easypost/services/claim.rb, lib/easypost/services/customs_info.rb, lib/easypost/services/customs_item.rb, lib/easypost/services/end_shipper.rb, lib/easypost/services/event.rb, lib/easypost/services/insurance.rb, lib/easypost/services/order.rb, lib/easypost/services/parcel.rb, lib/easypost/services/pickup.rb, lib/easypost/services/referral_customer.rb, lib/easypost/services/refund.rb, lib/easypost/services/report.rb, lib/easypost/services/scan_form.rb, lib/easypost/services/shipment.rb, lib/easypost/services/tracker.rb, lib/easypost/services/user.rb, lib/easypost/services/webhook.rb
Rdoc was getting confused about the constant taking precedence over the class name for classes containing a `MODEL_CLASS`, this change tells rdoc not to document the constant which wasn't needed to begin with which removes the unnecessary `MODEL_CLASS` doc generation and cleans up the resulting output.
Also bumps rdoc to use newer stylized docs output.
Closes #317 
See new output: 
=> fix: rdoc generation excluding MODEL_CLASS (closes #317)

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGELOG.md, easypost.gemspec, lib/easypost/services/user.rb, lib/easypost/services/webhook.rb, spec/cassettes/user/EasyPost_Services_User_update_brand_updates_the_authenticated_user_s_brand.yml, spec/cassettes/webhook/EasyPost_Services_Webhook_create_creates_a_webhook.yml, spec/cassettes/webhook/EasyPost_Services_Webhook_update_updates_a_webhook.yml, spec/spec_helper.rb, spec/support/fixture.rb, spec/support/vcr.rb, spec/user_spec.rb, spec/webhook_spec.rb
- Adds Ruby 3.4 support
- Corrects the HTTP verb for updating a brand from `GET` to `PATCH`
- Adds param tests for webhooks
=> fix: webhook update params

.github/workflows/ci.yml, CHANGELOG.md, Makefile, Rakefile, bin/easypost-irb, easypost.gemspec, lib/easypost/services/report.rb, lib/easypost/services/user.rb, spec/address_spec.rb
- Drops Ruby 2.6 support
- Removes deprecated functions
- Removes unmaintained, undocumented, and untested `irb`
- Bumps all dev deps
- Fixes TODOs
- Removes unused `Rakefile`
- Fixes address verification assertion
=> !chore: breaking changes in prep for v7

CHANGELOG.md, lib/easypost/services/carrier_account.rb, spec/carrier_account_spec.rb, spec/cassettes/carrier_account/EasyPost_Services_CarrierAccount_create_creates_a_FedEx_account.yml, spec/cassettes/carrier_account/EasyPost_Services_CarrierAccount_create_creates_a_UPS_account.yml, spec/cassettes/carrier_account/EasyPost_Services_CarrierAccount_create_creates_an_Amazon_account.yml
=> feat: Amazon carrier account creation
