EasyPost/easypost-ruby

- lib/easypost/util.rb
2.7.2 WebHooks failed with last refactoring
> Fix NoMethodError: undefined method `index' for nil:NilClass

- .travis.yml
- README.md
I'll delete the `circle.yml` in a subsequent PR
> build in travis-ci

- lib/easypost/customs_info.rb
- lib/easypost/customs_item.rb
- lib/easypost/order.rb
- lib/easypost/pickup.rb
Removed `all()` unpaginated endpoints.
> Made unpaginated methods raise not implemented errors

- lib/easypost.rb
- lib/easypost/object.rb
- spec/easypost_spec.rb
- spec/spec_helper.rb
> fix issue when using client without explictly setting up

- .github/workflows/ci.yml
- .travis.yml
- README.md
If it passes, I'll remove the travis workflow and edit the badge and whatnot
> add github workflow for ci

- .github/workflows/ci.yml
See https://github.com/actions/setup-ruby/issues/80 for some motivation.
> use ruby/setup-ruby instead of actions/setup-ruby to simplify CI yml

- CHANGELOG.md
- README.md
* Adds releasing info to the README
* Cleans up the README to follow the styles of our other CLs
* Makes the CHANGELOG markdown
> docs: Add releasing info, make CHANGELOG markdown

- easypost.gemspec
Bumps development dependencies.
> chore: bump development dependencies

- spec/cassettes/tracker/EasyPost_Tracker_create_list_creates_trackers_in_bulk_from_a_list_of_tracking_codes.yml
- spec/easy_post/tracker_spec.rb
Adds a missing test for the tracking `create_list` method.
> test: create_list tracking test

- spec/carrier_account_spec.rb
- spec/spec_helper.rb
- spec/support/authenticate.rb
- spec/user_spec.rb
* reset to test before each example is run
> test: remove state pollution due to before hooks setting class variables

- spec/batch_spec.rb
- spec/cassettes/batch/EasyPost_Batch_create_creates_a_batch.yml
- spec/cassettes/batch/EasyPost_Batch_retrieve_retrieves_a_batch.yml
Fixes a couple batch test params.
> fix: batch test params

- lib/easypost/connection.rb
Given that so many consumers are using threading, remove the optimization for single-thread consumers and restore the original behavior pre-#142 
Closes #151
> fix: just establish a new connection on every request

- lib/easypost/address.rb
- spec/address_spec.rb
- spec/cassettes/address/EasyPost_Address_all_retrieves_all_addresses.yml
- spec/cassettes/address/EasyPost_Address_create_and_verify_creates_a_verified_address.yml
- spec/cassettes/address/EasyPost_Address_create_creates_an_address.yml
- spec/cassettes/address/EasyPost_Address_create_creates_an_address_with_verify_param.yml
- spec/cassettes/address/EasyPost_Address_create_creates_an_address_with_verify_strict_param.yml
- spec/cassettes/address/EasyPost_Address_retrieve_retrieves_an_address.yml
- spec/cassettes/address/EasyPost_Address_verify_verifies_an_already_created_address.yml
- spec/spec_helper.rb
- spec/support/fixture.rb
This PR removes code that adds `strict` and `verify_strict` to the URL query when the API method is POST. 
re-record existing cassettes and all tests pass.
> remove additional code that put parameter in url query.

- easycop.yml
- easypost.gemspec
Pins rubocop for compatibility.
Rubocop passes locally
> fix: rubocop pin

- CHANGELOG.md
- lib/easypost.rb
- lib/easypost/beta/beta.rb
- lib/easypost/beta/beta_referral.rb
- lib/easypost/util.rb
- spec/cassettes/referral/EasyPost_BetaReferral_all_retrieve_all_referral_users.yml
- spec/cassettes/referral/EasyPost_BetaReferral_update_email_updates_a_referral_user.yml
- spec/referral_spec.rb
Add beta functions for White Label API
Create a new folder called `beta` with Referral class
`Referral` class has these new function:  `create()`, `update_email()`, `all()`, and `add_credit_card()`
Since there is some sensitive info, E2E test for `create()` and `add_credit_card()`
> feat: adds partner and referral beta classes and functions

- lib/easypost.rb
- lib/easypost/beta.rb
- lib/easypost/beta/referral.rb
- spec/beta/referral_spec.rb
- spec/cassettes/beta/referral/EasyPost_Beta_Referral_all_retrieve_all_referral_users.yml
- spec/cassettes/beta/referral/EasyPost_Beta_Referral_update_email_updates_a_referral_user.yml
* create beta namespace by creating module first
* then require files
> refactor: beta namespace

- lib/easypost/resource.rb
- lib/easypost/user.rb
- lib/easypost/webhook.rb
- spec/cassettes/carrier_account/EasyPost_CarrierAccount_save_updates_a_carrier_account.yml
- spec/cassettes/user/EasyPost_User_update_brand_updates_the_authenticated_user_s_brand.yml
- spec/cassettes/user/EasyPost_User_update_updates_a_user.yml
- spec/cassettes/webhook/EasyPost_Webhook_update_updates_a_webhook.yml
Swapped update brand, carrier, user, and webhook endpoints to use patch instead
> swapped put to patch

- lib/easypost/payment_method.rb
- spec/cassettes/payment_method/EasyPost_PaymentMethod_all_retrieves_all_payment_methods.yml
Add the missing conditional statement to check if the `id` is null when retrieving payment methods.
> add missing conditional to check if there is a payment method.

- spec/credit_card_spec.rb
changed CreditCardFund test from 20 to 2000
> Update CreditCardFund test

- .github/workflows/ci.yml
- Makefile
- README.md
- easypost.gemspec
Adds `Brakeman` as our security analysis tool. Also adds the long-missing Makefile which will make running these tools much easier and uniform with our normal process.
> feat: adds brakeman for security analysis

- spec/beta/referral_spec.rb
- spec/cassettes/beta/referral/EasyPost_Beta_Referral_all_retrieve_all_referral_users.yml
changed the referral test all method to account for new referral_customers keys. 
Closes #193 
Updated cassettes. 
> updated referral test

- CHANGELOG.md
- lib/easypost/shipment.rb
- spec/cassettes/shipment/EasyPost_Shipment_generate_form_generates_a_form_for_a_shipment.yml
- spec/shipment_spec.rb
- spec/support/fixture.rb
Adds `generate_form` function to the Shipment object allowing users to specify
> feat: adds generate_form function

- spec/error_spec.rb
Fixes a test assertion for error comparison.
> fix: error test assertion

- lib/easypost/payment_method.rb
Change the deprecation wording to make it more concise
N/A
> change the deprecation wording

- spec/address_spec.rb
- spec/cassettes/address/EasyPost_Address_create_creates_an_address_with_an_array_verify_param.yml
- spec/cassettes/address/EasyPost_Address_create_creates_an_address_with_verify_strict_param.yml
Adds stronger address verification tests.
Switches base case verifications to use a bool and adds a new array test to ensure both work.
> chore: stronger address verification tests

- .github/workflows/ci.yml
- .gitignore
- Makefile
- README.md
Makes the Makefile uniform with other libs and adds a `release` target.
Tested the targets to ensure they work as expected
> chore: add release target to Makefile and make it uniform

- spec/support/fixture.rb
> fix: typos in fixtures

- spec/support/fixture.rb
Uses the new event-body JSON file fixture
> fix: use new event-body fixture

- CHANGELOG.md
- Makefile
> fix: gem location in Makefile publish target

- .github/workflows/ci.yml
- README.md
Adds coveralls to report coverage of the master branch
> feat: adds coveralls

- .github/workflows/ci.yml
- Makefile
- README.md
- easypost.gemspec
- spec/spec_helper.rb
Adds a function that runs for each test that will warn when a cassette is expired (180 days)
Set the expiration to `90` days and various cassettes threw warnings about being expired before setting it back to the real value of 180 days
> feat: expire cassettes after 180 days

- CHANGELOG.md
- lib/easypost.rb
- lib/easypost/event.rb
- lib/easypost/payload.rb
- lib/easypost/util.rb
- spec/cassettes/event/EasyPost_Event_retrieve_a_payload_retrieve_a_payload.yml
- spec/cassettes/event/EasyPost_Event_retrieve_all_payloads_retrieve_all_payloads.yml
- spec/event_spec.rb
- New functions to retrieve all payloads or a specific payload for a specific event
- New unit tests, cassettes
- New Payload class, JSON deserialization mapping
- New unit tests, cassettes
> feat: Add functions to retrieve event payload(s)

- CHANGELOG.md
- lib/easypost/pickup.rb
- spec/cassettes/pickup/EasyPost_Pickup_all_retrieves_all_pickups.yml
- spec/pickup_spec.rb
- Add function in retrieve all pickups
- New unit test, cassette
> feat: Add function in retrieve all pickups

- README.md
> docs: add lib link to README

- lib/easypost/billing.rb
Changes the `primary_or_secondary` param name to `priority` which works in this lib because these are positional params and not named so there will be no breaking change.
NA
> fix: priority param name

- spec/cassettes/refund/EasyPost_Refund_create_creates_a_refund.yml
- spec/cassettes/refund/EasyPost_Refund_retrieve_retrieves_a_refund.yml
- spec/refund_spec.rb
Passes tracking codes as a list instead of string
> fix: refund test

- README.md
> chore: add support policy

- .github/workflows/ci.yml
> chore: add ruby 3.2 to matrix

- CHANGELOG.md
- lib/easypost/error.rb
- spec/error_spec.rb
Improves Error Deserialization to dynamically handle edge cases that have a bad format
Add unit tests
> Improves Error Deserialization

- CHANGELOG.md
- lib/easypost/errors/api/api_error.rb
- lib/easypost/errors/api/bad_request_error.rb
Maps 400 status code responses to the new `BadRequestError` class
Closes #275
NA
> feat: adds new BadRequestError class and maps to 400 status codes

- CHANGELOG.md
- lib/easypost/constants.rb
- lib/easypost/services/api_key.rb
- lib/easypost/services/user.rb
- spec/api_key_spec.rb
- spec/cassettes/api_key/EasyPost_Services_ApiKey_all_retrieves_all_API_keys.yml
- spec/cassettes/api_key/EasyPost_Services_ApiKey_retrieve_api_keys_for_user_retrieves_child_user_s_API_keys_as_a_parent.yml
- spec/cassettes/api_key/EasyPost_Services_ApiKey_retrieve_api_keys_for_user_retrieves_the_authenticated_user_s_API_keys.yml
- spec/user_spec.rb
Migrate API Key-related functions out of `user` service into `api_key` service
- Update unit tests, cassettes accordingly
> [chore] Migrate API Key-related functions to `api_key` service

- CHANGELOG.md
- lib/easypost/services/insurance.rb
- spec/cassettes/insurance/EasyPost_Services_Insurance_refund_cancels_an_insurance.yml
- spec/client_spec.rb
- spec/insurance_spec.rb
Add a refund function in the insurance service
Added a unit test
> Add refund function in insurance service

- .github/workflows/ci.yml
> [chore] Add Ruby 3.3 to CI matrix

- CHANGELOG.md
- Makefile
- lib/easypost/services/carrier_account.rb
- spec/carrier_account_spec.rb
- spec/cassettes/carrier_account/EasyPost_Services_CarrierAccount_create_creates_an_UPS_account.yml
- spec/cassettes/carrier_account/EasyPost_Services_CarrierAccount_update_updates_an_ups_account.yml
Update carrier create and update function to account UPS endpoints
Add unit tests to make sure we are hitting to the right endpoints
> Update carrier create and update function to account UPS endpoints

- .github/workflows/ci.yml
- .github/workflows/release.yml
Now that we have an API Key saved to GitHub Actions for RubyGems, we can use it to automate releasing this lib. Once a GitHub Release has been created (which automatically creates an accompanying tag), GitHub Actions will build and publish the library to RubyGems.
I've used this workflow for other repos for years.
> feat: automated releasing

- spec/webhook_spec.rb
> chore: bump examples submodule
